// <auto-generated />
using System;
using GameMaker.DataStorageImplementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameMaker.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20181230080152_GameDBMigration2")]
    partial class GameDBMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameMaker.Implementations.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameSessonId");

                    b.Property<string>("PlayerName");

                    b.Property<int>("PlayerScore");

                    b.Property<int>("PlayerState");

                    b.HasKey("PlayerId");

                    b.HasIndex("GameSessonId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameMaker.Interfaces.Game", b =>
                {
                    b.Property<string>("SessonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameType");

                    b.Property<int>("Gamestate");

                    b.Property<int>("MaxAllowedPlayer");

                    b.Property<int>("NumberOfPlayers");

                    b.Property<Guid>("TurnPlayerId");

                    b.Property<string>("UserId");

                    b.HasKey("SessonId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameMaker.Implementations.Player", b =>
                {
                    b.HasOne("GameMaker.Interfaces.Game")
                        .WithMany("Players")
                        .HasForeignKey("GameSessonId");
                });
#pragma warning restore 612, 618
        }
    }
}
